spring.application.name=orderpay
server.port=8080
spring.datasource.url=jdbc:h2:mem:orderpaydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
app.jwt.secret=9a2f8c4e6b0d71f3e8b925a4c747d8f285d3941a5256c7d3108493d0a256f17c
app.jwt.expiration-ms=86400000
